- name: install kubernetes library
  block:
    - name: install pip
      ansible.builtin.apt:
        name: python3-pip
    - name: get k8s
      ansible.builtin.pip:
        name: kubernetes

- name: create config
  ansible.builtin.command:
    cmd: sh -c "microk8s config > .kube/config"
    creates: .kube/config

- name: create deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cv
        labels:
          app: cv
        namespace: default
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: cv
        template:
          metadata:
            labels:
              app: cv
          spec:
            imagePullSecrets:
            - name: github-registry
            containers:
            - name: cv
              image: ghcr.io/lucykowal/cv:main
              imagePullPolicy: Always
              ports:
              - containerPort: 80
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "50m"
                limits:
                  memory: "128Mi"
                  cpu: "100m"

- name: create service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: cv-service
        namespace: default
      spec:
        selector:
          app: cv
        ports:
        - protocol: TCP
          port: 8001
          targetPort: 80
        type: ClusterIP

- name: create ingress
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: cv-ingress
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /
        namespace: default
      spec:
        rules:
        - host: "luuucyyy.net"
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: cv
                  port:
                    number: 8001
