- name: bootstrap server

  remote_user: root
  hosts: hcloud

  vars_files:
    - config.yml

  tasks:
    - name: setup tailscale
      import_role:
        name: tailscale
      tags: [ "tailscale" ]

    - name: setup openresty
      import_role:
        name: openresty
      tags: [ "nginx" ]

    - name: setup containers
      import_role:
        name: docker
      tags: [ "docker" ]
