- name: bootstrap server

  remote_user: root
  hosts: hcloud

  vars_files:
    - config.yml

  tasks:
    - name: setup kubernetes
      import_role:
        name: microk8s
      tags: [ "k8s" ]

    - name: setup openresty
      import_role:
        name: openresty
      tags: [ "nginx" ]
