- name: install snap
  ansible.builtin.apt:
    name: snapd
    state: present

- name: install microk8s
  community.general.snap:
    name: microk8s
    classic: true
    state: present

- name: add user to microk8s group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: microk8s
    append: yes

- name: wait for microk8s
  ansible.builtin.command: microk8s status --wait-ready
  register: microk8s_ready
  retries: 10
  delay: 30

- name: enable microk8s addons
  ansible.builtin.command: microk8s enable {{ item }}
  loop: "{{ microk8s_addons }}"
