- name: install snap
  ansible.builtin.apt:
    name: snapd
    state: present

- name: install docker
  community.general.snap:
    name: docker
    state: present

- name: set up container registry
  community.docker.docker_login:
    registry: ghcr.io
    username: "{{ github_username }}"
    password: "{{ github_token }}"
  vars:
    github_username: "{{ vault_github_username }}"
    github_token: "{{ vault_github_token }}"

- name: deploy containers
  community.docker.docker_container:
    name: cv
    image: ghcr.io/lucykowal/cv:main
    pull: true
    state: started
    recreate: true
    exposed_ports: 
      - "80"
    published_ports:
      - 8080:80
